### PR TITLE
#287 replace forEach() with native for-loops

### PR DESCRIPTION
**Pull request by coffeeandwork**

### CODE REVIEW

**Comment by leonardorafael** [comment]
Nice!

**Review by laurentpayot — COMMENTED** [review]
What?? What are the benefits of `for` loops compared to `forEach`?
`forEach` is more declarative and has a terser syntax than a `for` loop, am I wrong? Is it faster? If yes by how much?
Ideally we should use `map` to avoid side effects but I digress... Can someone tell me how `for` loops are an improvement over `forEach`?

**Comment by laurentpayot** [comment]
Oh I just read #287 :man_facepalming:  So the reason is performance. Ah that’s a good reason for such a syntax trade off...

**Comment by leonardorafael** [comment]
I'm a lover of readable and small size code. But this makes me to think about it https://github.com/beercss/beercss/issues/287#issuecomment-2057792453

**Pull request merged**
