### PR TITLE
Release v3.4.3

### PR DESCRIPTION
**Pull request by leonardorafael**
### CHANGELOG 3.4.3
<a href="https://github.com/beercss/beercss">Size</a>

 ### 🚀 Added
- Added support for standard navigation drawer (https://m3.material.io/components/navigation-drawer/guidelines#38800092-0149-4251-ac75-4ce8a144042a).
- Added main layouts section on homepage (https://m3.material.io/foundations/layout/applying-layout/window-size-classes)
- Added main layouts docs
- Updated navigations section on homepage
- Updated navigations docs

### 🩹 Fixed
- The dialog elements were behind navigation rails, now will be above

```html
// Added support for standard navigation drawer

<nav class="drawer left|right">
  <a>
    <i>home</i>
    <span>Home</span>
  </a>
  <a>
    <i>search</i>
    <span>Search</span>
  </a>
  <a>
    <i>more_vert</i>
    <span>More</span>
  </a>
</nav>

// inside dialog/article
<dialog>
  <nav class="drawer">
    <a>
      <i>home</i>
      <span>Home</span>
    </a>
    <a>
      <i>search</i>
      <span>Search</span>
    </a>
    <a>
      <i>more_vert</i>
      <span>More</span>
    </a>
  </nav>
</dialog>
```

### Main layouts section
image

### Standard navigation drawer
image

### CODE REVIEW

**Comment by laurentpayot** [comment]
In the [codepen example](https://codepen.io/leo-bnu/pen/yLKLPxj) I couldn’t see the difference between `<nav class="left m l">` and `<nav class="drawer left m l">` :thinking:

**Comment by laurentpayot** [comment]
Hi @leonardorafael thanks for these new features :smiley:

A few remarks:
- In the [codepen example](https://codepen.io/leo-bnu/pen/yLKLPxj) I couldn’t see the difference between `<nav class="left m l">` and `<nav class="drawer left m l">` :thinking:
- Would it be possible to have an automagic class that would allow a unique menu section to be at the bottom on small screens and on the side on larger screens? Having to generate two separate menus creates duplicate IDs errors. To get only one menu I had to overwrite Beercss CSS with media queries styles, and that’s not a good solution…

**Comment by leonardorafael** [comment]
> Hi @leonardorafael thanks for these new features 😃
> 
> A few remarks:
> 
> * In the [codepen example](https://codepen.io/leo-bnu/pen/yLKLPxj) I couldn’t see the difference between `<nav class="left m l">` and `<nav class="drawer left m l">` 🤔
> * Would it be possible to have an automagic class that would allow a unique menu section to be at the bottom on small screens and on the side on larger screens? Having to generate two separate menus creates duplicate IDs errors and bloats the page. To get only one menu I had to overwrite Beercss CSS with media queries styles, and that’s not a good solution…

Hi @laurentpayot , thanks!

I created another codepen with the next release modifications here https://codepen.io/leo-bnu/pen/ZEweJYj

Yes, the navs are independent today. We do that because the content can be very different between then. But in some cases I think we can try to add a class `responsive` in `nav` to do the trick for us.

**Comment by laurentpayot** [comment]
@leonardorafael Thanks, I see now. The `drawer` class changes the `div` text content positioning. Neat :+1: 

> in some cases I think we can try to add a class responsive in nav to do the trick for us.

Great idea, I will try that when I have time.

**Review by laurentpayot — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
