### PR TITLE
breaking

### PR DESCRIPTION
**Pull request by bartduisters**
convert from --size: 1px to --size: 16px - divide all existing rem values by 16

This commit will not break anything inside of this library, but any user who used any rem values in their own project, will need to change the value to `current rem value / 16`.

### CODE REVIEW

**Comment by bartduisters** [comment]
This probably won't get merged, but, what is the idea behind having font-size 1px, to then use the rems as if they are px?

**Comment by leonardorafael** [comment]
> This probably won't get merged, but, what is the idea behind having font-size 1px, to then use the rems as if they are px?

Initially yes. And this helped to maintain the 10kb gzip of css in final bundle too. Other users want to use 16px, so we will try merge it, soon.

**Comment by bartduisters** [comment]
If any consumer of beercss went along with the 1rem = 1px, they'll have to refactor their code.
So probably you'd need to do a major release.

To have it backwards compatible, we could add a `--font-size` variable. And then keep everything exactly as is. But it would require a calc() for each existing rem value. Which is probably an issue in itself. And I noticed while refactoring to 16px, that some rems are calculated in code, not in css, which would require a separate workaround.

**Comment by amery** [comment]
I wrote a non-too-little script to divide all `rem` values by 16 to help me with this transition

```sh
#!/bin/sh

set -eu

set --
for n in $(git grep rem | sed -e 's|\([0-9]\+rem\)|\n\1\n|g' | sed -n -e 's|\([0-9]\+\)rem|\1|p' | sort -un); do
        v=$(echo 000$(( ${n}0000 / 16 )) | sed -e 's|\(....\)$|.\1|' -e 's|^0\+||' -e 's|0\+$||' -e 's|\.$||' -e 's|^\.|0\.|' -e 's|\.|\\.|')
        echo "$n -> $v"
        set -- "$@" -e "s;\([^0-9.]\)$n\(rem\);\\1|$v|\\2;g"
done

git grep -l rem | xargs -r sed -i "$@" -e "s;|\([0-9.]\+\)|\(rem\);\1\2;g"
```

**Comment by bartduisters** [comment]
> I wrote a non-too-little script to divide all `rem` values by 16 to help me with this transition
> 
> ```shell
> #!/bin/sh
> 
> set -eu
> 
> set --
> for n in $(git grep rem | sed -e 's|\([0-9]\+rem\)|\n\1\n|g' | sed -n -e 's|\([0-9]\+\)rem|\1|p' | sort -un); do
>         v=$(echo 000$(( ${n}0000 / 16 )) | sed -e 's|\(....\)$|.\1|' -e 's|^0\+||' -e 's|0\+$||' -e 's|\.$||' -e 's|^\.|0\.|' -e 's|\.|\\.|')
>         echo "$n -> $v"
>         set -- "$@" -e "s;\([^0-9.]\)$n\(rem\);\\1|$v|\\2;g"
> done
> 
> git grep -l rem | xargs -r sed -i "$@" -e "s;|\([0-9.]\+\)|\(rem\);\1\2;g"
> ```

If others run that script, don't forget to manually go into `beer.ts`. There is a calculation there that will not be found by the script.

```ts
let width = hasClass(label, "active") ? label.offsetWidth : Math.round(label.offsetWidth / 1.33);
width = width / 16; // 16px = 1rem, originally 1px = 1rem, hence the division
```

**Comment by amery** [comment]
will you rebase it or should I? @bartduisters

**Comment by amery** [comment]
doing the eslint part on a separate commit can reduce the 16px part down to a readable change

**Comment by bartduisters** [comment]
> will you rebase it or should I? @bartduisters

Please do!

**Comment by amery** [comment]
@bartduisters https://github.com/beercss/beercss/commit/73f9a554f25e71ec59756c3e648cba5b647160a0 sits on top of https://github.com/beercss/beercss/pull/101

please review

**Comment by bartduisters** [comment]
> @bartduisters https://github.com/amery/beercss/tree/convert-to-font-size-16px updated to the latest #101 for you to review [7d0ed0f](https://github.com/beercss/beercss/commit/7d0ed0faef77b5040f9404006f2307aea910bf1d) if it still fully reflects your work

Seems fine, had one comment about `0.75rem` instead of `.75rem`, but can be ignored. It's just a preference.

**Comment by amery** [comment]
> Seems fine, had one comment about `0.75rem` instead of `.75rem`, but can be ignored. It's just a preference.

do you mean you prefer with or without the leading zero? @bartduisters

@leonardorafael thoughts about the whole thing?

**Comment by bartduisters** [comment]
> > Seems fine, had one comment about `0.75rem` instead of `.75rem`, but can be ignored. It's just a preference.
> 
> do you mean you prefer with or without the leading zero? @bartduisters
> 
> @leonardorafael thoughts about the whole thing?

I prefer with the leading zero. But I prefer consistency more. So the maintainer can decide.

**Comment by leonardorafael** [comment]
Hi guys,

For me it's ok. I usually don't use eslints but I like the idea and your job. Do your best my friends. If I can propose something here, try follow the best practices of open source community, please.

Congrats @bartduisters @amery

**Comment by amery** [comment]
@leonardorafael thanks, after you decide about https://github.com/beercss/beercss/pull/101 I'll submit one switching _stylelint_ rules to choose leading zeros to make @bartduisters [happier](https://github.com/amery/beercss/tree/convert-to-font-size-16px), and we can then update this PR's branch accordingly :)

**Comment by leonardorafael** [comment]
@bartduisters, @amery 

Can you rerun that scripts above on latest `dev` branch? Maybe another PR? There are much conflits to resolve 🙁

**Comment by amery** [comment]
@leonardorafael please check https://github.com/beercss/beercss/pull/103 before this one gets rebuild. 

after that @bartduisters can reset his branch against the latest `dev` and cherry-pick e4aac37472c848a7794fae267c1df4f4fc364fcd to update this PR conflict-free

**Comment by amery** [comment]
@bartduisters my hope we to use cherry-pick instead of a merge to keep the history clean...

**Comment by bartduisters** [comment]
I'll cherry pick

**Comment by bartduisters** [comment]
@amery What's the flow for this? I'm used to just merging (I'm one of those folks that are fine with merge commits).

I did a hard reset to upstream dev, but how do I then cherry-pick a commit that is still on the origin branch?

**Comment by amery** [comment]
> @amery What's the flow for this? I'm used to just merging (I'm one of those folks that are fine with merge commits).
> 
> I did a hard reset to upstream dev, but how do I then cherry-pick a commit that is still on the origin branch?

```sh
git remote add upstream https://github.com/beercss/beercss
git remote add amery https://github.com/amery/beercss
git remote update --prune
git checkout convert-to-font-size-16px
git reset --hard amery/convert-to-font-size-16px
git rebase upstream/dev
git push --force origin convert-to-font-size-16px
```

or after #103 is merged
```sh
git reset --hard upstream/dev
git cherry-pick f063e08a9788ef10a75b22bdb56fd7c2373d5b08
git push --force origin convert-to-font-size-16px
```

**Comment by bartduisters** [comment]
Thanks, I'm processing it, gotta go now, I'll try to open it later today. But this is a horrid experience, going through each commit one by one in the rebase. I'll take a merge commit any day over this experience 🤢

**Comment by amery** [comment]
> Thanks, I'm processing it, gotta go now, I'll try to open it later today. But this is a horrid experience, going through each commit one by one in the rebase. I'll take a merge commit any day over this experience nauseated_face

I already went through all that, you shouldn't need. my branches are already rebased on top of upstream/dev

**Comment by bartduisters** [comment]
Odd, I did the steps you provided and it prompted me to do those commits. Perhaps I forgot something/did something wrong. And you honestly enjoy this process? (really curious!)

**Comment by bartduisters** [comment]
I did a reset to upstread dev, did the changes necessary. Force pushed that on my branch. I guess that is why. Perhaps I should just grab your branch and rebase upstread dev on that one, force push that one.

**Comment by amery** [comment]
> Odd, I did the steps you provided and it prompted me to do those commits. Perhaps I forgot something/did something wrong. And you honestly enjoy this process? (really curious!)

the purpose is to avoid having hundreds of lines on the git history that don't reflect the state that was agreed after the discussion. this is the main history between git and.... svn. history is recorded for future reviews, not to match 100% all the mistakes done during while preparing the feature

**Comment by bartduisters** [comment]
Actually, I don't know if I did the right thing in package.json, can you double check?

**Comment by amery** [comment]
> This should be ok @amery?
you can see above 7 commits, the first 4 and the last aren't related to the topic being discussed here, but they will disappear after you **rebase** on top of the new `dev` once #103 is merged.
then you have two commits. one implements the change discussed here and the next fixes a mistake.
in my world those two should be squashed into a single commit, to avoid polluting history with mistakes known at the time of merging the PR.
the easiest way to sort that is using the `squash` command on an interactive rebase, `git rebase -i upstream/dev`

**Comment by bartduisters** [comment]
I had to resolve some stuff here on GitHub, I pulled those changes, that did a merge. So there is again a merge commit.

And isn't there an option to just squash on merge? Instead of having to do all this stuff manually.

**Comment by amery** [comment]
@bartduisters make a workspace on gitpod.io and I can help you sort it but it's basically running this now
```sh
git checkout convert-to-font-size-16px
git remote update --prune
git reset --hard amery/convert-to-font-size-16px
git push --force origin convert-to-font-size-16px
```

and this after #103 is merged
```sh
git remote update --prune
git rebase upstream/dev
git push --force origin convert-to-font-size-16px
```

**Comment by amery** [comment]
@bartduisters much better. see how pretty `git log --oneline --graph upstream/dev..convert-to-font-size-16px` looks like now

**Comment by bartduisters** [comment]
I understand what I did wrong now. I missed the reset --hard to your branch the first time around. I'll read up a bit more to be less of a pita the next time.

**Comment by leonardorafael** [comment]
I will merge it and test on dev later.

**Comment by bartduisters** [comment]
https://github.com/beercss/beercss/issues/84 
This issue can be closed I guess

**Pull request merged**
