### PR TITLE
 #216 string constants in beer.ts

### LINKED ISSUE #216: Use string constants in beer.ts
String constants may have performance benefits.

Suppose we have the following function:

```javascript
const sayHello = (name) => {
  return "Hello " + name + "!";
}
```

Each time `sayHello()` is called, these 3 string objects get created:
1. `"Hello "` string object
2. `"!"` string object
3.  and finally the string object resulting from the concatenation operation `"Hello " + name + "!"`.

If we were to rewrite the above code in the following way:

```javascript
const PREFIX = "Hello ";
const SUFFIX = "!";
const sayHello2 = (name) => {
  return PREFIX + name + SUFFIX;
}
```
When the above code is loaded in the web browser, the`PREFIX` and `SUFFIX` objects get created once up front and then those objects get reused each time `sayHello2()` gets called. This means that every next time `sayHello2()` gets called, only 1 of the 3 new string objects from `sayHello()` get created. Fewer new objects created means lower memory consumption, and less work for the garbage collector.

Therefore, in the spirit of keeping this library lean-and-mean, it wouldn't be a bad idea to extract out all the string literals into global constants.

### PR DESCRIPTION
**Pull request by coffeeandwork**
helps reduce the amount of string object creation/destruction in the runtime js code.

### CODE REVIEW

**Comment by coffeeandwork** [comment]
Here is a benchmark I have put together to illustrate the general idea, feel free to play with it. The code is not minified, so you should be able to view source to check it out: https://jsperftests.pages.dev/

**Comment by ahmnot** [comment]
On the Brave browser, I have 59662.00000 milliseconds for 100000000 iterations of task1() (the inline literal), and 62127.00000 milliseconds for 100000000 iterations of task2() (the "global constants"). We sould trace a graph of performance given the number of iterations

**Comment by leonardorafael** [comment]
Hi @coffeeandwork in my tests I'm not getting much difference between solutions.

Did I made the test wrong? https://jsperf.app/kayoca

image
image

**Comment by coffeeandwork** [comment]
> Hi @coffeeandwork in my tests I'm not getting much difference between solutions.
> 
> Did I made the test wrong? https://jsperf.app/kayoca
> 
> image image

Thank you for taking the time @leonardorafael. 

I notice that in your test you are incrementing the counter and writing its value to the DOM. (Is that correctly?) I wonder if the DOM api calls are far heavier than `ONE + TWO` and `"one" + "two"` and are overshadowing the functions under test, and also have a large variance in their performance based on conditions of your machine, graphics card, and other programs running that may also be trying to paint to the screen.

In my test setup at https://jsperftests.pages.dev/ I have tried to run the actual test in a worker thread to isolate it away from any of the distractions of the main browser thread. I also don't make any DOM API calls in the middle of my iterations, I only make them before and after the test run where we want to measure elapsed time.

I am not an expert in how javascript engines perform runtime optimizations, but if I were to guess, `"one" + "two"` gets transformed in place to `"onetwo"` by the js engine, so in the "without const" version, the optimized code may not be performing a string concatenation operation at all. However, I also suspect that in the "with const" example, `ONE + TWO` may also get optimized by the compiler into a singular value, but I am less sure of this possibility. (On an unrelated note, it would be an interesting test to see if there is a difference in performance if `ONE` and `TWO` are defined using `let` instead of `const`.)

To prevent the compiler from performing the above-mentioned optimizations (if they do so at all), I have introduced an `ARRAY_OF_RANDOM_WORDS` in my test code, where, on every next iteration of the loop I am concatenating a randomly chosen element of `ARRAY_OF_RANDOM_WORDS` to an inline string literal (and in another function to a global string constant). There may be a small variance introduced here depending on how different js engines implement js lists, but the variance should be minimal since they they appear to be sparse array / hashtable type based implementations afaik.

To further eliminate the possibility that the `ARRAY_OF_RANDOM_WORDS`, which was being defined as a hard coded constant array of strings, that may also go through some optimizations that I am unfamiliar with, I have created a second version of the test where the list of random words comes from a `<textarea/>` that you can modify (its no longer a hard coded constant). Its parsed as a comma separated list of values, feel free to play with it here: https://v2.jsperftests.pages.dev/

I have tried the test on a few different devices, and below are some performance numbers I have observed. The variance appears to be high in these measurements, so take the numbers with a pinch of salt. If I find time, I will try to do some regression analysis across the number of iterations for the `with const` and `without const` variable, as suggested by @ahmnot (thank you for your feedback).

I am using the incognito/private windows (not sure whether this matters), and I clear the cache, and do a full page reload. I also keep the network tab open and visually inspect each request to ensure it is not being served from the browser cache to ensure that the cache clearing actually worked):

Device: Apple Mac (M1 MX) - 13.5.2 (22G91) - 64 GB Memory
Browser: Google Chrome 117.0.5938.92 (Official Build) (arm64)
Number of iterations: 40000

On first page load
without const elapsed time: 32 milliseconds
with const elapsed time: 19.7 milliseconds

after hitting the "Run" button again (at this time, the javascript code has long been loaded into the browser, and been called 40000 times and has had time to optimize, and for garbage collector to run)
without const elapsed time: 19.3 milliseconds
with const elapsed time: 15.6 milliseconds
(variance was very high here, so a few times I saw the elapsed times for the "with const" case as being higher than the "without const" case, but most of the time "with const" had a shorter elapsed time.

Device: Apple Mac (M1 MX) - 13.5.2 (22G91) - 64 GB Memory
Browser: Firefox 118.0.1 (64-bit)
Number of iterations: 40000

On first page load
without const elapsed time: 22 milliseconds
with const elapsed time: 16 milliseconds

after hitting the "Run" button again:
without const elapsed time: 11 milliseconds
with const elapsed time: 10 milliseconds

Device: Apple Mac (M1 MX) - 13.5.2 (22G91) - 64 GB Memory
Browser: Safari 16.6 (18615.3.12.11.2)
Number of iterations: 40000

On first page load
without const elapsed time: 22 milliseconds
with const elapsed time: 14 milliseconds

after hitting the "Run" button again:
without const elapsed time: 14 milliseconds
with const elapsed time: 11 milliseconds

Device: Apple Mac (M1 MX) - 13.5.2 (22G91) - 64 GB Memory
Browser: Brave v1.58.131 
Number of iterations: 40000

On first page load
without const elapsed time: 30 milliseconds
with const elapsed time: 19 milliseconds

after hitting the "Run" button again:
without const elapsed time: 42 milliseconds
with const elapsed time: 20 milliseconds

I also tried to run this on a super old low powered Nokia phone.
device: Nokia 2V 8GB Storage, 1 GB RAM (Model Number 11EVWX11APP)
OS: Android V9

On first page load
without const elapsed time: 377 milliseconds
with const elapsed time: 261 milliseconds

after hitting the "Run" button again:
without const elapsed time: 266.4 milliseconds
with const elapsed time: 214.6 milliseconds

The pattern looked similar or iphone and a few other android phones. All of these measurements could be done much more rigorously of course. I am not sure whether its worth doing that for this PR. The other thing we haven't done so far is measure memory to see whether there is a reduction in overall memory usage (between garbage collector runs) by the use of global constants as compared to inline string literals. I will see if there is an easy way to measure that and report back. 

Do we have enough information already to make a decision on this? Thank you all for your help.

**Comment by coffeeandwork** [comment]
As a larger point, I agree that this is not a huge optimization. I was going through the code and I thought I saw this small opportunity, so I went for it. The long list of constants at the top of the beer.ts file, and their use in the code down below indeed makes the code a bit more difficult to read. Some options:

1. We abandon this PR, and,
1.1. not worry about this sort of optimization at all, or
1.2. use a transpile-time plugin that might be able to do this. I have not been able to find one so far, but I can keep looking for one. If any of you know of one, that would be great, please let me know.
2. We keep the PR, but,
2.1. I move the constants into other files and reorganize them to make the code more readable, or,
2.2 We keep the constants in their existing place and I add documentation for each constant.
2.3 Merge the PR as is.

I would like to propose that (1.2) may not be a good idea because we may want to maintain control over when we use constants and when we use string literals. For example, it may be worth it to use global string constants in certain functions because those functions get called often, and it may be better to opt to keep string literals in other places where the functions are called less often, where the increased readability of the code from string literals has the highest net benefit.

**Comment by KicKerBNU** [comment]
For me the results of the tests are inconclusive, sometimes i get better performance for literals and other from globals..
tested on MacOS and Windows.

I have also made some tests with the entire bundle on jsperf comparing the two generated bundles. The same happen with the loading time testing the home page with the two different bundles... 😕

**Pull request closed without merging**
