### PR TITLE
#86 Self host Google Fonts and Material Symbols

### PR DESCRIPTION
**Pull request by coffeeandwork**
With this PR, Roboto font files and Material Symbols woff2 files will be loaded using relative urls to the location of beer.min.css file instead of relying on the Google hosted version as default behavior. (I have created a new PR because the [previous PR](https://github.com/beercss/beercss/pull/91), now closed, got mangled up.)

### CODE REVIEW

**Review by laurentpayot — COMMENTED** [review]
Why removing `blinkmacsystemfont` and `-apple-system` fonts? MD3 specs  have a link to [MD2 docs explaining that systems fonts are a good choice for iOS](https://m2.material.io/design/typography/understanding-typography.html#system-fonts:~:text=iOS%20applications%20should%20use%20Apple%E2%80%99s%20San%20Francisco%20font).

**Comment by coffeeandwork** [comment]
> Why removing `blinkmacsystemfont` and `-apple-system` fonts? MD3 specs have a link to [MD2 docs explaining that systems fonts are a good choice for iOS](https://m2.material.io/design/typography/understanding-typography.html#system-fonts:~:text=iOS%20applications%20should%20use%20Apple%E2%80%99s%20San%20Francisco%20font).

`system-ui` is a replacement for both  `blinkmacsystemfont` and `-apple-system` fonts as described [here](https://css-tricks.com/snippets/css/system-font-stack/) and I quote:

> Chrome and Safari have [recently shipped](https://www.chromestatus.com/feature/5640395337760768) “system-ui” which is a generic font family that can be used in place of “-apple-system” and “BlinkMacSystemFont” in the following examples.

**Comment by laurentpayot** [comment]
> `system-ui` is a replacement for both `blinkmacsystemfont` and `-apple-system` fonts

Good to know, thanks :+1:

**Comment by coffeeandwork** [comment]
@laurentpayot and/or @leonardorafael are you guys good with this PR? If not, any suggestions?

**Comment by laurentpayot** [comment]
@coffeeandwork Looks good to me but I am a mere user/contributor...

**Comment by leonardorafael** [comment]
It's good to me too, I will merge this in dev. Thanks @coffeeandwork

**Comment by coffeeandwork** [comment]
Awesome. Thank you @leonardorafael

**Pull request merged**
