### PR TITLE
#218 color picker

### PR DESCRIPTION
**Pull request by coffeeandwork**
Demo: https://codepen.io/coffeeandwork/pen/MWZXVYL

### CODE REVIEW

**Comment by leonardorafael** [comment]
Nice add @coffeeandwork ,

In my opinion we can use the same logic of input files here. 

In addition to use restricted in `field` element, we can use inside any other elements too (like input files).

How about that https://codepen.io/leo-bnu/pen/abPKQRZ?

**Comment by leonardorafael** [comment]
Oh, I just see a new bug on our latest release 😔

Can we use this PR to fix it too?

image

**Comment by coffeeandwork** [comment]
> Nice add @coffeeandwork ,
> 
> In my opinion we can use the same logic of input files here.
> 
> In addition to use restricted in `field` element, we can use inside any other elements too (like input files).
> 
> How about that https://codepen.io/leo-bnu/pen/abPKQRZ?

That looks very nice. I like what you have done. I will update the PR.

**Comment by leonardorafael** [comment]
Hi @coffeeandwork ,

I pushed some commits in dev branch. I was trying to reduce the size after rtl implementation. I caught some bugs and fixed it. I took advantage and fixed the input file bug and implemented the input color too. I will close this PR ok?

**Before 72.68kb**
before

**After 70.07kb**
after

**Comment by coffeeandwork** [comment]
sounds good. Thanks. I was working on a few ideas for the color picker. Ill create a new issue for it.

**Pull request closed without merging**
